spring:
  application:
    name: spring-cloud-client
  profiles: peer1
server:
  port: 8010
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/
    fetch-registry: false
