spring:
  application:
    name: spring-cloud-eureka
  profiles: 8
server:
  port: 8002
eureka:
  instance:
    hostname: 192.168.0.8
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.0.193:8002/eureka/
  server:
    enable-self-preservation: false