spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: TTT-HJ
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/